<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="unittest.loader.ModuleImportFailure-20150121013827" tests="1" time="0.000">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="unittest.loader.ModuleImportFailure" name="test_docktst" time="0.000">
		<error message="Failed to import test module: tests.test_docktst
Traceback (most recent call last):
  File &quot;/usr/lib/python2.7/unittest/loader.py&quot;, line 254, in _find_tests
    module = self._get_module_from_name(name)
  File &quot;/usr/lib/python2.7/unittest/loader.py&quot;, line 232, in _get_module_from_name
    __import__(name)
  File &quot;/var/www/python_ci/three_most_important_things-master/tests/test_docktst.py&quot;, line 48, in &lt;module&gt;
    suite = unittest.TestLoader().loadTestsFromTestCase(TestView,TestModels) #replace htmlreportsdemo with your class name
TypeError: loadTestsFromTestCase() takes exactly 2 arguments (3 given)
" type="ImportError">
<![CDATA[ImportError: Failed to import test module: tests.test_docktst
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/var/www/python_ci/three_most_important_things-master/tests/test_docktst.py", line 48, in <module>
    suite = unittest.TestLoader().loadTestsFromTestCase(TestView,TestModels) #replace htmlreportsdemo with your class name
TypeError: loadTestsFromTestCase() takes exactly 2 arguments (3 given)

]]>		</error>
	</testcase>
</testsuite>
